This is the Python code of Example 3.5 in the book:

FIBER-REINFORCED COMPOSITES
Materials, Manufacturing, and Design

by: P.K. Mallick (2008) by Taylor & Francis Group, LLC

This code:
(C) Joris Remmers (2013-2019)

## Example 3.6

A thin plate is subjected to a biaxial stress field of $\sigma_{xx}=1\,$GPa and $\sigma_{yy}=0.5\,$GPa. Calculate the strains if the plate is made of (a) steel, (b) a $0^{\circ}$ unidirectional boron–epoxy composite, and (c) a $45^{\circ}$ unidirectional boron–epoxy composite.

## Solution

Import the correct functions from the composite module:

In [17]:
from composite import TransverseIsotropic,mixMaterials
from numpy     import array,dot

Steel may be considered as an isotropic material with Young's modulus $E=207\,$GPa and Poisson's ratio $\nu=0.33$. Please not that this can be modelled as a transversely Isotropic material, with onlt a single Young's modulus.

In [18]:
carbon = TransverseIsotropic( 220e9,0.2,91.7e9)
print(carbon)

  Material Properties:
  ---------------------------------
  E1   220000000000.0
  E2   220000000000.0
  nu12 0.2
  G12  91700000000.0  a1   0.0
  a2   0.0


Boron Epoxy is a composite material with a Young's modulus $E_1=207\,$GPa; $E_2=19\,$GPa; a Poisson's ratio $\nu_{12}=0.21$ and a shear modulus $G_{12}=6.4\,$GPa. The two elastic moduli are entered as a list.

In [19]:
epoxy  = TransverseIsotropic( 3.6e9,0.35,1.33e9)
print(epoxy)

  Material Properties:
  ---------------------------------
  E1   3600000000.0
  E2   3600000000.0
  nu12 0.35
  G12  1330000000.0  a1   0.0
  a2   0.0


The applied stress is introduced as a numpy array:

In [20]:
compmat = mixMaterials( carbon , epoxy , 0.6 )
print(compmat)

  Material Properties:
  ---------------------------------
  E1   133440000000.0
  E2   8784383318.54481
  nu12 0.26
  G12  3254202465.4463954  a1   0.0
  a2   0.0


a) The strain in the steel plate is:

In [21]:
compmat.getQ()

array([[1.34036479e+11, 2.29414891e+09, 0.00000000e+00],
       [2.29414891e+09, 8.82364964e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.25420247e+09]])

b) The strain in the $0^{\circ}$ unidirectional boron–epoxy composite is:

In [22]:
compmat.getU()

array([5.57731866e+10, 6.26064145e+10, 1.56568776e+10, 1.79510265e+10,
       1.89110801e+10])

c) The strain in the $45^{\circ}$ unidirectional boron–epoxy composite is:

In [23]:
compmat.getQbar( 45. )

array([[4.01163090e+10, 3.36079041e+10, 3.13032073e+10],
       [3.36079041e+10, 4.01163090e+10, 3.13032073e+10],
       [3.13032073e+10, 3.13032073e+10, 3.45679576e+10]])

In [24]:
compmat.getQbar( -45. )

array([[ 4.01163090e+10,  3.36079041e+10, -3.13032073e+10],
       [ 3.36079041e+10,  4.01163090e+10, -3.13032073e+10],
       [-3.13032073e+10, -3.13032073e+10,  3.45679576e+10]])