This is the Python code of Example 3.15 in the book:

FIBER-REINFORCED COMPOSITES
Materials, Manufacturing, and Design

by: P.K. Mallick (2008) by Taylor & Francis Group, LLC

This code:
(C) Joris Remmers (2013-2019)


## Example 3.13

Determine the curvatures of a two-layer unsymmetric $\lbrack 0/90\rbrack$ laminate after it
is cooled from the curing temperature to the room temperature. The material is
T-300 carbon fiber in an epoxy matrix for which $\alpha_{11}=-0.5\times10^6$ m/m per $^{\circ}$C 
$\alpha_{22}=12\times10^6$ m/m per $^{\circ}$C. Other material properties are the same as those
in Example 3.6. The thickness of each layer is $t=1$\,mm, and the temperature drop is $\Delta T=-100^{\circ}$C.

## Solution

Import the correct functions from the composite module and required mathermatical operators:

In [1]:
from composite    import TransverseIsotropic,mixMaterials,Laminate,stressTransformation
from numpy        import array,dot,zeros
from numpy.linalg import inv

As demonstrated in Example 3.6 and 3.7, the ply properties and laminate can be obtained as: 

In [10]:
compmat = TransverseIsotropic( [133.4e9,8.784e9],0.26,3.254e9,[-0.5e-6,12e-6])

print(compmat)


lam = Laminate()

lam.addMaterial( 'composite' , compmat )

lam.addLayer( 'composite' , 0 , 1e-3 )
lam.addLayer( 'composite' , 90 , 1e-3 )

print(lam)

  Elastic Properties:
  -----------------------------------------------------------
  E1     :     1.334e+11 , E2     :     8.784e+09 
  nu12   :          0.26 , G12    :     3.254e+09 

  Thermal expansion coefficients:
  -----------------------------------------------------------
  alpha1 :    -5.000e-07 , alpha2 :     1.200e-05 

  Laminate properties
  -----------------------------------------------------------
  layer   thick orient.  material
  -----------------------------------------------------------
      0   0.001      0   composite
      1   0.001     90   composite



The Qbar matrices of both layers are:

In [11]:
Q0  = compmat.getQbar(0)
Q90 = compmat.getQbar(90)

print("The matrix Q0 : \n",Q0,"\n")
print("The matrix Q90: \n",Q90,"\n")

The matrix Q0 : 
 [[1.33996453e+11 2.29405142e+09 0.00000000e+00]
 [2.29405142e+09 8.82327471e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.25400000e+09]] 

The matrix Q90: 
 [[ 8.82327471e+09  2.29405142e+09 -1.29955146e-09]
 [ 2.29405142e+09  1.33996453e+11  7.66594618e-06]
 [-1.29955146e-09  7.66594618e-06  3.25400000e+09]] 



In [12]:
A   = lam.getA()
B   = lam.getB()
D   = lam.getD()

print("The matrix A  : \n",A,"\n")
print("The matrix B  : \n",B,"\n")
print("The matrix D  : \n",D,"\n")

The matrix A  : 
 [[ 1.42819728e+08  4.58810285e+06 -1.29955146e-12]
 [ 4.58810285e+06  1.42819728e+08  7.66594618e-09]
 [-1.29955146e-12  7.66594618e-09  6.50800000e+06]] 

The matrix B  : 
 [[-6.25865893e+04  0.00000000e+00 -6.49775729e-16]
 [ 0.00000000e+00  6.25865893e+04  3.83297309e-12]
 [-6.49775729e-16  3.83297309e-12  0.00000000e+00]] 

The matrix D  : 
 [[ 4.76065760e+01  1.52936762e+00 -4.33183819e-19]
 [ 1.52936762e+00  4.76065760e+01  2.55531539e-15]
 [-4.33183819e-19  2.55531539e-15  2.16933333e+00]] 



Now Ts and Tss can be calculated:

In [13]:
Ts  = lam.getTs()
Tss = lam.getTss()

print("The vector Ts  : \n",Ts,"\n")
print("The vector Tss : \n",Tss,"\n")

The vector Ts  : 
 [ 6.52626612e+01  6.52626612e+01 -8.82981856e-15] 

The vector Tss : 
 [ 7.21009402e-02 -7.21009402e-02 -4.41490928e-18] 



Calculating the matrices C1 and D1, we obtain

In [16]:
A1,B1,C1,D1 = lam.getInverseMatrices()

kappa = -100*(dot(C1,Ts)+dot(D1,Tss))  # -100 degrees difference

print(kappa)

[-5.11739221e-01  5.11739221e-01  6.26699799e-17]
