This example is discussed during the lecture on classical laminate theory in the course:

Composite and Lightweight Materials (4MM00)

at Eindhoven University of Technology

This code:
(C) Joris Remmers (2013-2023)

## Example: Stresses in the Titan Vessel

Consider a pressure vessel that is made of a carbon fibre reinforced plastic. The fibre reinforced plastic consists of uni-directional carbon fibres embedded in an epoxy matrix. 

The fibre volume fraction $V_f=0.6$. The properties of the transverse isoptric fibre are: $E_{\rm fL} = 220\,$GPa ; 
$E_{\rm fT} = 20\,$GPa ; $\nu_{\rm f} = 0.2$ ; $G_{\rm f} = 91.7\,$GPa.

The properties of the isotropic epoxy matrix are $E_{\rm m} = 3.6\,$GPa ; $\nu_{\rm f} = 0.35$ ; 
$G_{\rm f} = 1.33\,$GPa.

The carbon fibre is used to construct a pressure vessel with a radius $R=0.8$,m that consists 480 layers with alternating orientation +/- 45$^{\circ}$. Calculate the stresses in a single layer when the cylinder is loaded by an external pressure of 450 atmosphere, or 46 MPa.

## Solution

In [1]:
from composite import TransverseIsotropic,mixMaterials,Laminate,stressTransformation

For this carbon fiber composite material, the carbon fibers and the epoxy matrix are modeled as separate transversely isotropic materials. The T-300 carbon fibers have Young's Moduli $E_1=220\,$GPa,  $E_2=22\,$GPa, a Poisson's ratio $\nu_{12}=0.2$ and a Shear Modulus $G_{12}=91.7\,$GPa. The epoxy matrix may be considered isotropic with Young's modulus $E=3.6\,$GPa, Poisson's ratio $\nu=0.35$ and Shear Modulus $G_{12}=1.33\,$GPa. 

In [2]:
carbon = TransverseIsotropic( [220e9,22e9],0.2,91.7e9)
epoxy  = TransverseIsotropic( 3.6e9,0.35,1.33e9)

The properties of carbon and epoxy are:

In [3]:
print(carbon)
print(epoxy)


  Elastic Properties:
  -----------------------------------------------------------
  E1     :     2.200e+11 , E2     :     2.200e+10 
  nu12   :          0.20 , G12    :     9.170e+10 

  Thermal expansion coefficients:
  -----------------------------------------------------------
  alpha1 :     0.000e+00 , alpha2 :     0.000e+00 


  Elastic Properties:
  -----------------------------------------------------------
  E1     :     3.600e+09 , E2     :     3.600e+09 
  nu12   :          0.35 , G12    :     1.330e+09 

  Thermal expansion coefficients:
  -----------------------------------------------------------
  alpha1 :     0.000e+00 , alpha2 :     0.000e+00 



The composite consists of 60\% fibres and 40\% epoxy. The properties of the composite can be calculated by simple homogensiation.

In [4]:
udcomp = mixMaterials( carbon , epoxy , 0.6 )
    

Store the thermal expension coefficient of the material

In [5]:
udcomp.setAlpha( [-5e-6 , 12e-6] )
print("The UD material properties are:",udcomp)

The UD material properties are: 
  Elastic Properties:
  -----------------------------------------------------------
  E1     :     1.334e+11 , E2     :     7.226e+09 
  nu12   :          0.26 , G12    :     3.254e+09 

  Thermal expansion coefficients:
  -----------------------------------------------------------
  alpha1 :    -5.000e-06 , alpha2 :     1.200e-05 



In [6]:
lam = Laminate()

lam.addMaterial( 'UD' , udcomp )

for i in range(120):    
    lam.addLayer( 'UD' ,  -45.0 , 0.25e-3 )
    lam.addLayer( 'UD' ,   45.0 , 0.25e-3 )

for i in range(120):
    lam.addLayer( 'UD' ,   45.0 , 0.25e-3 )
    lam.addLayer( 'UD' ,  -45.0 , 0.25e-3 )

print(lam)

  Laminate properties
  -----------------------------------------------------------
  layer   thick orient.  material
  -----------------------------------------------------------
      0   0.00025   -45.0   UD  
      1   0.00025   45.0   UD  
      2   0.00025   -45.0   UD  
      3   0.00025   45.0   UD  
      4   0.00025   -45.0   UD  
      5   0.00025   45.0   UD  
      6   0.00025   -45.0   UD  
      7   0.00025   45.0   UD  
      8   0.00025   -45.0   UD  
      9   0.00025   45.0   UD  
     10   0.00025   -45.0   UD  
     11   0.00025   45.0   UD  
     12   0.00025   -45.0   UD  
     13   0.00025   45.0   UD  
     14   0.00025   -45.0   UD  
     15   0.00025   45.0   UD  
     16   0.00025   -45.0   UD  
     17   0.00025   45.0   UD  
     18   0.00025   -45.0   UD  
     19   0.00025   45.0   UD  
     20   0.00025   -45.0   UD  
     21   0.00025   45.0   UD  
     22   0.00025   -45.0   UD  
     23   0.00025   45.0   UD  
     24   0.00025   -45.0   UD  
     25

The A,B and D matrix of this system is:

In [7]:
print("A = ",lam.getA())
print("B = ",lam.getB())
print("D = ",lam.getD())

A =  [[4.73914201e+09 3.95813342e+09 6.59376383e-07]
 [3.95813342e+09 4.73914201e+09 6.59376383e-07]
 [6.59376383e-07 6.59376383e-07 4.12234947e+09]]
B =  [[ 1.89756975e-08  1.74622983e-08 -1.49593689e-08]
 [ 1.74622983e-08  1.29221007e-08 -1.49593689e-08]
 [-1.49593689e-08 -1.49593689e-08  1.30385160e-08]]
D =  [[5686970.41302189 4749760.10297332  -28502.42911251]
 [4749760.10297332 5686970.41302189  -28502.42911251]
 [ -28502.42911251  -28502.42911251 4946819.35958648]]


The total system of equations is:
  \begin{equation}
  \begin{bmatrix}
  {\bf N} \\
  {\bf M}
  \end{bmatrix}
  =
  \begin{bmatrix}
  {\bf A} & {\bf B} \\
  {\bf B} & {\bf D} \\  
  \end{bmatrix}
  \begin{bmatrix}
  {\bf \epsilon}_0 \\
  {\bf \kappa}
  \end{bmatrix}
  \end{equation}
The external load $N$ and $M$ is equal to:
  \begin{equation}
  {\bf N} = \lbrack pR/2 , pR , 0 \rbrack\qquad\qquad {\bf M} = \lbrack 0 , 0 , 0 \rbrack
  \end{equation}

As $M$ is equal to 0 and $B$ is equal to zero (because of symmetry), the equation reduces to:

  \begin{equation}
      {\bf N} = {\bf A}{\bf\epsilon}_0
  \end{equation}
  Solving for ${\bf \epsilon}_0$ gives

In [8]:
import numpy as np

p = -46e6
R = 0.8
N = np.array([p*R/2,p*R,0])

A = lam.getA()

epsilon = np.dot ( np.linalg.inv(A) , N )

print("The strain is :", epsilon)


The strain is : [ 8.60623233e-03 -1.49530475e-02  1.01518323e-18]


As each layer has the same orientation (+ or -45$^{\circ}$) and the curvature is equal to zero, all layers are exerted to the same stress state

\begin{equation}
  {\bf \sigma}_j = \bar{\bf Q}_j{\bf \epsilon}_0
\end{equation}

In [9]:
sigma = np.dot( lam.getQbar(0) , epsilon )

print("The stress in each layer in global coordinates is equal to : ",sigma)

sigmaloc = stressTransformation(sigma, -45 )

print("The stress in each layer in local coordinates is equal to : ",sigmaloc)


The stress in each layer in global coordinates is equal to :  [-1.53333333e+08 -3.06666667e+08  2.00999612e+08]
The stress in each layer in local coordinates is equal to :  [-4.30999612e+08 -2.90003882e+07  7.66666667e+07]
