This is the Python code of Example 3.7 in the book:

FIBER-REINFORCED COMPOSITES
Materials, Manufacturing, and Design

by: P.K. Mallick (2008) by Taylor & Francis Group, LLC

This code:
(C) Joris Remmers (2013-2019)


## Example 3.7

Determine [A], [B], and [D] matrices for :
* (a) a [+45/-45] angle-ply laminate, 
* (b) a [+45/-45]S symmetric laminate, and 
* (c) a [+45/0/-45] unsymmetric laminate.

Each lamina is 6 mm thick and contains 60 vol% of T-300 carbon fiber in an epoxy matrix. Use the same material properties as in Example 3.6.

## Solution

Import the correct functions from the composite module:

In [1]:
from composite import TransverseIsotropic,mixMaterials,Laminate
from numpy     import array,dot

For this carbon fiber composite material, the carbon fibers and the epoxy matrix are modelled as separate transversely isotropic materials. The T300 carbon fibers have Young's Moduli $E_1=220\,$GPa, $E_2=220\,$GPa, a Poisson's ratio $\nu_{12}=0.2$ and a Shear Modulus  $G_{12}=91.7\,$GPa. 
The epoxy matrix may be considered isotropic with Young's modulus $E=3.6\,$GPa,Poisson's ratio $\nu=0.35$ and Shear Modulus  $G_{12}=1.33\,$GPa. 
As demonstrated in Example 3.6, the ply properties can be obtained as: 

In [2]:
carbon = TransverseIsotropic( 220e9,0.2,91.7e9)
epoxy  = TransverseIsotropic( 3.6e9,0.35,1.33e9)

compmat = mixMaterials( carbon , epoxy , 0.6 )

print("Material properties of the composite material:\n\n",compmat,"\n")

Material properties of the composite material:

   Elastic Properties:
  -----------------------------------------------------------
  E1     :     1.334e+11 , E2     :     8.784e+09 
  nu12   :          0.26 , G12    :     3.254e+09 

  Thermal expansion coefficients:
  -----------------------------------------------------------
  alpha1 :     0.000e+00 , alpha2 :     0.000e+00 
 



Now we can construct a laminate out of different laminae with these single ply properties. For a a [+45/-45] angle-ply laminate with 6mm layer thickness, this can be done as:

In [3]:
lam = Laminate()

lam.addMaterial( 'composite' , compmat )

lam.addLayer( 'composite' , 45. , 6e-3 )
lam.addLayer( 'composite' , -45. , 6e-3 )

Using the functions getA, getB and getD, the for this laminate can be calculated:

In [4]:
print("Laminate [45/-45]\n")
print("A matrix:\n\n",lam.getA(),"\n")
print("B matrix:\n\n",lam.getB(),"\n")
print("D matrix:\n\n",lam.getD(),"\n")

Laminate [45/-45]

A matrix:

 [[4.81395708e+08 4.03294849e+08 0.00000000e+00]
 [4.03294849e+08 4.81395708e+08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.14815492e+08]] 

B matrix:

 [[       0.               0.        -1126915.4616971]
 [       0.               0.        -1126915.4616971]
 [-1126915.4616971 -1126915.4616971        0.       ]] 

D matrix:

 [[5776.74849698 4839.53818693    0.        ]
 [4839.53818693 5776.74849698    0.        ]
 [   0.            0.         4977.78589951]] 



This procedure can be repeated for the [+45/-45]S symmetric, and 
 [+45/0/-45] unsymmetric laminate:

In [5]:
lam.removeAllLayers()

lam = Laminate()

lam.addMaterial( 'composite' , compmat )

lam.addLayer( 'composite' , 45. , 6e-3 )
lam.addLayer( 'composite' , -45. , 6e-3 )
lam.addLayer( 'composite' , -45. , 6e-3 )
lam.addLayer( 'composite' , 45. , 6e-3 )

print("Laminate [45/-45]s\n")
print("A matrix:\n\n",lam.getA(),"\n")
print("B matrix:\n\n",lam.getB(),"\n")
print("D matrix:\n\n",lam.getD(),"\n")

lam.removeAllLayers()

lam = Laminate()

lam.addMaterial( 'composite' , compmat )

lam.addLayer( 'composite' , 45. , 6e-3 )
lam.addLayer( 'composite' , 0. , 6e-3 )
lam.addLayer( 'composite' , -45. , 6e-3 )

print("Laminate [45/0/-45]s\n")
print("A matrix:\n\n",lam.getA(),"\n")
print("B matrix:\n\n",lam.getB(),"\n")
print("D matrix:\n\n",lam.getD(),"\n")


Laminate [45/-45]s

A matrix:

 [[ 9.62791416e+08  8.06589698e+08 -1.19209290e-07]
 [ 8.06589698e+08  9.62791416e+08 -1.19209290e-07]
 [-1.19209290e-07 -1.19209290e-07  8.29630983e+08]] 

B matrix:

 [[ 4.65661287e-10  2.32830644e-10 -4.65661287e-10]
 [ 2.32830644e-10  4.65661287e-10 -2.32830644e-10]
 [-4.65661287e-10 -2.32830644e-10  2.32830644e-10]] 

D matrix:

 [[46213.98797583 38716.30549544 27045.97108073]
 [38716.30549544 46213.98797583 27045.97108073]
 [27045.97108073 27045.97108073 39822.28719604]] 

Laminate [45/0/-45]s

A matrix:

 [[ 1.28561458e+09  4.17059742e+08 -5.96046448e-08]
 [ 4.17059742e+08  5.34337606e+08 -5.96046448e-08]
 [-5.96046448e-08 -5.96046448e-08  4.34340706e+08]] 

B matrix:

 [[-6.98491931e-10  0.00000000e+00 -2.25383092e+06]
 [ 0.00000000e+00  0.00000000e+00 -2.25383092e+06]
 [-2.25383092e+06 -2.25383092e+06  0.00000000e+00]] 

D matrix:

 [[21187.08923206 15769.79378783     0.        ]
 [15769.79378783 18933.25830867     0.        ]
 [    0.           